#spring:
#  datasource:
#    primary:
#      jdbc-url: jdbc:mysql://localhost:3306/user_local?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#      username: root
#      password: 123456abc
#      driver-class-name: com.mysql.jdbc.Driver
#    secondary:
#      jdbc-url: jdbc:mysql://localhost:3306/user_local1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#      username: root
#      password: 123456abc
#      driver-class-name: com.mysql.jdbc.Driver

spring:
  jta:
    atomikos:
      datasource:
        primarydb:
          unique-resource-name: primary
          xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
          xa-properties:
            url: jdbc:mysql://localhost:3306/user_local?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
            user: root
            password: 123456abc
          min-pool-size: 3
          max-pool-size: 10
          test-query: select 1 from dual #由于采用HikiriCP，用于检测数据库连接是否存活。

        secondarydb:
          unique-resource-name: secondary
          xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
          xa-properties:
            url: jdbc:mysql://localhost:3306/user_local1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
            user: root
            password: 123456abc
          min-pool-size: 3
          max-pool-size: 10
          test-query: select 1 from dual #由于采用HikiriCP，用于检测数据库连接是否存活。