spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/user_local?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456abc
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/user_local1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456abc
      driver-class-name: com.mysql.jdbc.Driver