#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          my-client-1:
#            client-id: "abcd"
#            client-secret: "123456"
#            client-name: "Client for user scope"
#            provider: "my-oauth-provider"
#            scope: "user"
#            redirect-uri: "http://www.baidu.com"
#            client-authentication-method: "basic"
#            authorization-grant-type: "authorization-code"
#        provider:
#          my-oauth-provider:
#            authorization-uri: "https://my-auth-server/oauth/authorize"
#

spring:
  redis:
    host: localhost
    password: 123456
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 8
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: 1000
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0


